-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- This file is a reference for checking database structure.

CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  talyer_owner_id uuid NOT NULL,
  mechanic_id uuid,
  invoice_number text NOT NULL UNIQUE,
  subtotal numeric NOT NULL,
  platform_fee numeric DEFAULT 0.00,
  total_amount numeric NOT NULL,
  talyer_net_amount numeric NOT NULL,
  status text DEFAULT 'generated'::text CHECK (status = ANY (ARRAY['generated'::text, 'sent'::text, 'paid'::text, 'disputed'::text, 'refunded'::text, 'cancelled'::text, 'pending'::text, 'accepted'::text, 'rejected'::text, 'completed'::text, 'processing'::text])),
  generated_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  paid_at timestamp with time zone,
  completed_at timestamp with time zone,
  payment_details jsonb DEFAULT '{}'::jsonb,
  service_details jsonb DEFAULT '{}'::jsonb,
  notes text,
  issued_at timestamp with time zone DEFAULT now(),
  provider_id uuid,
  due_date timestamp with time zone DEFAULT (now() + '7 days'::interval),
  items jsonb DEFAULT '[]'::jsonb,
  provider_net_amount numeric DEFAULT 0.00,
  tax numeric DEFAULT 0.00,
  accepted_at timestamp with time zone,
  available_payment_methods jsonb DEFAULT '["paymongo", "cash"]'::jsonb,
  selected_payment_method text CHECK (selected_payment_method = ANY (ARRAY['paymongo'::text, 'cash'::text, 'gcash'::text, 'paymaya'::text, 'bank_transfer'::text])),
  requires_cash_verification boolean DEFAULT false,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT invoices_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.user_profiles(id),
  CONSTRAINT invoices_talyer_owner_id_fkey FOREIGN KEY (talyer_owner_id) REFERENCES public.user_profiles(id),
  CONSTRAINT invoices_mechanic_id_fkey FOREIGN KEY (mechanic_id) REFERENCES public.user_profiles(id)
);

CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone_number character varying NOT NULL,
  profile_image_url text,
  status character varying DEFAULT 'active'::character varying,
  user_type character varying DEFAULT 'customer'::character varying CHECK (user_type::text = ANY (ARRAY['customer'::character varying, 'mechanic'::character varying, 'talyer_owner'::character varying, 'admin'::character varying, 'super_admin'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  current_latitude numeric,
  current_longitude numeric,
  is_available boolean DEFAULT true,
  role character varying DEFAULT 'customer'::character varying CHECK (role::text = ANY (ARRAY['customer'::character varying, 'mechanic'::character varying, 'talyer_owner'::character varying, 'admin'::character varying, 'super_admin'::character varying]::text[])),
  admin_permissions jsonb DEFAULT '[]'::jsonb,
  last_login_at timestamp with time zone,
  login_count integer DEFAULT 0,
  email_verified_at timestamp with time zone,
  account_status character varying DEFAULT 'active'::character varying CHECK (account_status::text = ANY (ARRAY['active'::character varying, 'pending_verification'::character varying, 'suspended'::character varying, 'banned'::character varying]::text[])),
  shop_id uuid,
  first_login_completed boolean DEFAULT false,
  password_change_required boolean DEFAULT false,
  temp_email text,
  email_change_token text,
  email_change_expires_at timestamp with time zone,
  last_password_change timestamp with time zone,
  failed_login_attempts integer DEFAULT 0,
  account_locked_until timestamp with time zone,
  registration_completed boolean DEFAULT false,
  profile_completion_score integer DEFAULT 0,
  profile_image_required boolean DEFAULT true,
  first_login_password_changed boolean DEFAULT false,
  account_verification_status text DEFAULT 'pending'::text CHECK (account_verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])),
  verification_documents jsonb DEFAULT '{}'::jsonb,
  business_permit_url text,
  drivers_license_url text,
  document_verification_status text DEFAULT 'pending'::text CHECK (document_verification_status = ANY (ARRAY['pending'::text, 'under_review'::text, 'verified'::text, 'rejected'::text])),
  document_verification_notes text,
  verified_by uuid,
  verified_at timestamp with time zone,
  can_login boolean DEFAULT false,
  requires_email_verification boolean DEFAULT true,
  shop_hours jsonb DEFAULT '{}'::jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  timezone text DEFAULT 'Asia/Manila'::text,
  preferred_language text DEFAULT 'en'::text,
  notification_preferences jsonb DEFAULT '{"sms": false, "push": true, "email": true}'::jsonb,
  rating numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);

CREATE TABLE public.mechanic_job_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mechanic_id uuid NOT NULL,
  service_request_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  shop_id uuid,
  job_title text NOT NULL,
  job_description text,
  job_status text NOT NULL,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  total_amount numeric,
  rating numeric,
  review_text text,
  job_duration_minutes integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  mechanic_earnings numeric DEFAULT 0.00,
  shop_earnings numeric DEFAULT 0.00,
  platform_fee numeric DEFAULT 0.00,
  fee_percentage_mechanic numeric DEFAULT 75.00,
  fee_percentage_shop numeric DEFAULT 20.00,
  fee_percentage_platform numeric DEFAULT 5.00,
  CONSTRAINT mechanic_job_history_pkey PRIMARY KEY (id),
  CONSTRAINT mechanic_job_history_mechanic_id_fkey FOREIGN KEY (mechanic_id) REFERENCES public.user_profiles(id),
  CONSTRAINT mechanic_job_history_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES public.service_requests(id),
  CONSTRAINT mechanic_job_history_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.user_profiles(id),
  CONSTRAINT mechanic_job_history_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
